import type { Metadata } from "next";
// Импортируем Inter вместо Geist
import { Inter } from "next/font/google";
import "./globals.css";

// Настраиваем шрифт с поддержкой кириллицы
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ru"
      className={`${inter.variable} h-full antialiased`}
    >
      {/* Добавили класс шрифта в body, чтобы он применился ко всему сайту */}
      <body className={`${inter.className} min-h-full flex flex-col`}>
        {children}
      </body>
    </html>
  );
}
